'use client';
import type { Metadata } from 'next';
import '@/styles/globals.scss';
import '@/styles/main.scss';
import { Provider } from 'react-redux';
import { store } from '@/redux/store';
import DynamicWalletProvider from '@/components/providers/DynamicWalletProvider';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClient = new QueryClient();

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <QueryClientProvider client={queryClient}>
            <DynamicWalletProvider>{children}</DynamicWalletProvider>
          </QueryClientProvider>
        </Provider>
      </body>
    </html>
  );
}
